dist: xenial

language: python

python:
  - 3.7

env:
  global:
    - TRAVIS_CI=true

install:
  - pip install codecov

script:
  - coverage run -m pytest tests/

# Push the results back to codecov
after_success:
  - codecov
